os: linux
language: python
python:
  - "2.7"
  - "3.6"
virtualenv:
  system_site_packages: true
dist: bionic
services:
  - xvfb
addons:
  apt:
    sources:
      - sourceline: 'deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic universe multiverse'
    update: true
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION < 3 ]]; then
    sudo apt install -y python-gtk2;
    else
    sudo apt install python-gi python-gi-cairo python3-gi python3-gi-cairo gir1.2-gtk-3.0;
    fi
install:
  - pip install -r requirements-dev.txt
script:
  - python atest/run.py -e no-xvfb -e gtk atest;
  - python atest/run.py -i gtk atest;
